// <auto-generated />
namespace rest.Migrations
{
    //using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    //[GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class UserToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserToken));
        
        string IMigrationMetadata.Id
        {
            get { return "202002110322485_User-Token"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
